### ISSUE TITLE
conflict with other plugin

### ISSUE THREAD

**Issue by Link0Darck** [Team-Inceptus/Novaconomy#105]
### Bug Type

Compatibility Issues

### Minecraft Version

1.20.1-R0.1-SNAAPSHOT 3859

### Description

Hello, I discovered this plugin but it conflicts with the vault plugin so if you can correct the problem that would be great
Thanks in advance

### Steps to Reproduce

type /economy create Yen ¥ amethyst_shard
flood consol error

### Expected Behavior

That the plugin works with vault because I cannot afford to remove vault because many other plugins use

### Actual Behavior

```
[14:17:19] [Craft Scheduler Thread - 0/ERROR]: [BungeeTabListPlus] Unexpected exception
java.lang.RuntimeException: Exception while querying data from Vault
Vault 1.7.3-b131

	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:35) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:47) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:375) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:305) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:133) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3859-Spigot-94e187b-f70a7b6]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3859-Spigot-94e187b-f70a7b6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Player is null
	at us.teaminceptus.novaconomy.api.player.NovaPlayer.<init>(NovaPlayer.java:74) ~[?:?]
	at us.teaminceptus.novaconomy.vault.VaultEconomy.getBalance(VaultEconomy.java:84) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:22) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.apply0(VaultBalanceProvider.java:48) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.apply0(VaultBalanceProvider.java:29) ~[?:?]
	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:33) ~[?:?]
	... 12 more
```

**Comment by GamerCoder215** [comment]
> ### Bug Type
> Compatibility Issues
> 
> ### Minecraft Version
> 1.20.1-R0.1-SNAAPSHOT 3859
> 
> ### Description
> Hello, I discovered this plugin but it conflicts with the vault plugin so if you can correct the problem that would be great Thanks in advance
> 
> ### Steps to Reproduce
> type /economy create Yen ¥ amethyst_shard flood consol error
> 
> ### Expected Behavior
> That the plugin works with vault because I cannot afford to remove vault because many other plugins use
> 
> ### Actual Behavior
> ```
> [14:17:19] [Craft Scheduler Thread - 0/ERROR]: [BungeeTabListPlus] Unexpected exception
> java.lang.RuntimeException: Exception while querying data from Vault
> Vault 1.7.3-b131
> 
> 	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:35) ~[?:?]
> 	at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
> 	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
> 	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:47) ~[?:?]
> 	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
> 	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:375) ~[?:?]
> 	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:305) ~[?:?]
> 	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:133) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3859-Spigot-94e187b-f70a7b6]
> 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3859-Spigot-94e187b-f70a7b6]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.IllegalArgumentException: Player is null
> 	at us.teaminceptus.novaconomy.api.player.NovaPlayer.<init>(NovaPlayer.java:74) ~[?:?]
> 	at us.teaminceptus.novaconomy.vault.VaultEconomy.getBalance(VaultEconomy.java:84) ~[?:?]
> 	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:22) ~[?:?]
> 	at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.apply0(VaultBalanceProvider.java:48) ~[?:?]
> 	at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.apply0(VaultBalanceProvider.java:29) ~[?:?]
> 	at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:33) ~[?:?]
> 	... 12 more
> ```
> 
> ### Additional Info
> _No response_

Unless you're running this command from the console, this shouldn't happen. If you aren't please comment below. If you are, then this is expected because I never properly checked if the command sent was a player or not, so this is indeed a bug.

**Comment by GamerCoder215** [comment]
Fixed in e669544.

**Comment by Link0Darck** [comment]
> 
Hello, The economy create command I sent it from my minecraft account in games and not from a console the problem I use vault and bungeetablistplus and which should display the money I have on me using vault or the fact that its error spam on the console

**Comment by Link0Darck** [comment]
thx @GamerCoder215
