### ISSUE TITLE
Bank

### ISSUE THREAD

**Issue by DSLZL** [Team-Inceptus/Novaconomy#140]
### Bug Type

Console Errors

### Minecraft Version

1.20.4

### Description

With the exception of the deposit, all other commands have errors

### Steps to Reproduce

/bank info
/bank balance
/bank withdraw

### Expected Behavior

fix it

### Actual Behavior

[20:38:16 INFO]: DSLZL issued server command: /bank withdraw 10 gold
[20:38:16 WARN]: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.la
ng.Long are in module java.base of loader 'bootstrap')
[20:38:16 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.player.NovaPlayer.getLastBankWithdraw(NovaPlayer.ja
va:432)
[20:38:16 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.abstraction.CommandWrapper.bankWithdraw(CommandWrapper.
java:995)
[20:38:16 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.CommandWrapperV2$BankCommands.bankWithdraw(CommandWrapp
erV2.java:568)
`[20:43:17 INFO]: DSLZL issued server command: /bank balances
[20:43:17 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[20:43:17 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[20:43:17 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[20:43:17 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[20:43:17 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:385)
[20:43:17 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[20:43:17 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.abstraction.CommandWrapper.bankBalances(CommandWrapper.
java:924)
[20:43:17 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.CommandWrapperV2$BankCommands.bankBalances(CommandWrapp
erV2.java:560)`
`[20:47:04 INFO]: DSLZL issued server command: /bank balance
[20:47:04 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[20:47:04 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[20:47:04 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[20:47:04 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[20:47:04 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:385)
[20:47:04 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[20:47:04 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.abstraction.CommandWrapper.bankBalances(CommandWrapper.
java:924)
[20:47:04 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.CommandWrapperV2$BankCommands.bankBalances(CommandWrapp
erV2.java:560)`
`[20:47:27 INFO]: DSLZL issued server command: /bank info
[20:47:27 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[20:47:27 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[20:47:27 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[20:47:27 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[20:47:27 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:385)
[20:47:27 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[20:47:27 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.abstraction.CommandWrapper.bankBalances(CommandWrapper.
java:924)
[20:47:27 WARN]:        at novaconomy-1.9.1-SNAPSHOT.jar//us.teaminceptus.novaconomy.CommandWrapperV2$BankCommands.bankBalances(CommandWrapp
erV2.java:560)`

**Comment by GamerCoder215** [comment]
Will test when I get the chance and fix for v1.9.2.

**Comment by GamerCoder215** [comment]
Fixed in 62de411. See [Using Experimental Versions](https://github.com/Team-Inceptus/Novaconomy/wiki/Using-Experiemental-Versions) on the wiki to learn how to use it.

**Comment by DSLZL** [comment]
> Fixed in 62de411. See [Using Experimental Versions](https://github.com/Team-Inceptus/Novaconomy/wiki/Using-Experiemental-Versions) on the wiki to learn how to use it.

Thank you.
