### ISSUE TITLE
Creating a Product that is made by plugins crashes the plugin

### ISSUE THREAD

**Issue by Pigioo** [Team-Inceptus/Novaconomy#69]
### Bug Type

Console Errors

### Minecraft Version

1.19.4

### Description

Plugin crashes when i make a product of a non vanilla item

### Steps to Reproduce

make a product thats with a plugin created item, (combatweaponryplus in my example

### Expected Behavior

For it to work like vanilla items

### Actual Behavior

Crashes the plugin

### Additional Info

16:59:01 INFO]: Pigio issued server command: /business addp 24
[16:59:02 ERROR]: NotSerializableException
[16:59:02 ERROR]: -----------
[16:59:02 ERROR]: org.bukkit.attribute.AttributeModifier
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[16:59:02 ERROR]: java.base/java.util.ArrayList.writeObject(ArrayList.java:866)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:02 ERROR]: java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:02 ERROR]: java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[16:59:02 ERROR]: java.base/java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:334)
[16:59:02 ERROR]: java.base/java.util.HashMap.writeObject(HashMap.java:1497)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:02 ERROR]: java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:02 ERROR]: java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1381)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[16:59:02 ERROR]: java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1944)
[16:59:02 ERROR]: java.base/java.util.HashMap.writeObject(HashMap.java:1497)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:02 ERROR]: java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:02 ERROR]: java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[16:59:02 ERROR]: java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1944)
[16:59:02 ERROR]: java.base/java.util.HashMap.writeObject(HashMap.java:1497)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:02 ERROR]: java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:02 ERROR]: java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[16:59:02 ERROR]: java.base/java.util.ArrayList.writeObject(ArrayList.java:866)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:02 ERROR]: java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:02 ERROR]: java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:02 ERROR]: java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
[16:59:02 ERROR]: java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[16:59:02 ERROR]: Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.writeBusiness(Business.java:791)
[16:59:02 ERROR]: Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.saveBusiness(Business.java:723)
[16:59:02 ERROR]: Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.addProduct(Business.java:519)
[16:59:02 ERROR]: Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.addProduct(Business.java:490)
[16:59:02 ERROR]: Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.GUIManager.lambda$static$31(GUIManager.java:496)
[16:59:02 ERROR]: Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.GUIManager.click(GUIManager.java:1401)
[16:59:02 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source)
[16:59:02 ERROR]: org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[16:59:02 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[16:59:02 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:59:02 ERROR]: io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[16:59:02 ERROR]: io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[16:59:02 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[16:59:02 ERROR]: net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3180)
[16:59:02 ERROR]: net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[16:59:02 ERROR]: net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[16:59:02 ERROR]: net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[16:59:02 ERROR]: net.minecraft.server.TickTask.run(TickTask.java:18)
[16:59:02 ERROR]: net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:59:02 ERROR]: net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[16:59:02 ERROR]: net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[16:59:02 ERROR]: net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[16:59:02 ERROR]: net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[16:59:02 ERROR]: java.base/java.lang.Thread.run(Thread.java:833)
[16:59:03 INFO]: Pigio issued server command: /bukkit:?
[16:59:05 INFO]: Pigio issued server command: /business
[16:59:05 WARN]: java.lang.IllegalStateException: java.io.EOFException
[16:59:05 WARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.getBusinesses(Business.java:1001)
[16:59:05 WARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.byOwner(Business.java:1055)
[16:59:05 WARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.abstraction.CommandWrapper.businessInfo(CommandWrapper.java:643)
[16:59:05 WARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.CommandWrapperV2$BusinessCommands.businessInfo(CommandWrapperV2.java:323)
[16:59:05 WARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.CommandWrapperV2$BusinessCommands.businessInfoDefault(CommandWrapperV2.java:320)
[16:59:05 WARN]: Caused by: java.io.EOFException
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3214)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1684)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2157)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1721)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:647)
[16:59:05 WARN]: 	at java.base/java.lang.Throwable.readObject(Throwable.java:912)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:05 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:05 WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readFatalException(ObjectInputStream.java:2541)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1739)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[16:59:05 WARN]: 	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:05 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:05 WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[16:59:05 WARN]: 	at java.base/java.util.HashMap.readObject(HashMap.java:1552)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:05 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:05 WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2157)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1721)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[16:59:05 WARN]: 	at java.base/java.util.HashMap.readObject(HashMap.java:1552)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:05 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:05 WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[16:59:05 WARN]: 	at java.base/java.util.HashMap.readObject(HashMap.java:1552)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:05 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:05 WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[16:59:05 WARN]: 	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:59:05 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:59:05 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:59:05 WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[16:59:05 WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[16:59:05 WARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.readBusiness(Business.java:875)
[16:59:05 W

https://user-images.githubusercontent.com/126029179/229315957-cb27c7a3-d5be-414f-80f7-ba49fdc60698.mp4

ARN]: 	at Novaconomy-1.7.0a-SNAPSHOT.jar//us.teaminceptus.novaconomy.api.business.Business.getBusinesses(Business.java:996)
[16:59:05 WARN]: 	... 4 more

https://user-images.githubusercontent.com/126029179/229315967-97a41893-a4dc-40b8-b835-647b2f97b524.mp4

**Comment by GamerCoder215** [comment]
Hello,
It seems like Spigot does not serialize AttributeModifiers for their serialization methods. It's a pretty quick fix, so I'll work on it soon.
